steps:
  # Build the pipeline container image.
  - name: 'golang:1.13.0'
    args: ['go', 'build', '-o', 'server', '-ldflags', '-w -s', '.']
    env: ['GOOS=linux', 'GOARCH=amd64', 'CGO_ENABLED=0', 'GOMODULE111=on']
    dir: 'server'
    waitFor: ['-']
  - name: 'node:10.16.0'
    entrypoint: yarn
    id: 'yarn-install'
    args: ['install']
    waitFor: ['-']
    dir: 'web'
  - name: 'node:10.16.0'
    entrypoint: yarn
    args: ['run', 'build']
    waitFor: ['yarn-install']
    dir: 'web'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-web:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/test-web:$COMMIT_SHA']
  - name: 'gcr.io/deploys-app/cli'
    args:
      - 'deployment'
      - 'set'
      - 'image'
      - 'buildchain-example-automate'
      - '-project=$_PROJECT_ID' # เอามาจาก Deploys.app นะครับ
      - '-image=gcr.io/$PROJECT_ID/test-web:$COMMIT_SHA'
images:
  - 'gcr.io/$PROJECT_ID/test-web:$COMMIT_SHA'
